// <auto-generated />
namespace ActivityTracker.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Achievements_Change_NameProperty_To_Description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Achievements_Change_NameProperty_To_Description));
        
        string IMigrationMetadata.Id
        {
            get { return "201712071348424_Achievements_Change_NameProperty_To_Description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
