// <auto-generated />
namespace ActivityTracker.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_Property_To_Entities_Achievement_And_Goal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Property_To_Entities_Achievement_And_Goal));
        
        string IMigrationMetadata.Id
        {
            get { return "201711280934350_Add_Property_To_Entities_Achievement_And_Goal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
